server:
  port: 8082
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
      config:
        enabled: true
        format: YAML
        prefix: config
  application:
    name: catalog-service
  datasource:
    url: jdbc:h2:mem:catalog-db
    username: admin
    password: pass
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    consul:
      enabled: true